name: HCL OneTest Performance

on: workflow_dispatch

jobs:
    Performance-Action:
        runs-on: self-hosted
        name: HCL OneTest Performance
        steps:
         - name: HCL OneTest Performance
           uses: anuraag-k/PerformanceTestAction@main
           with:
            workspace: C:\Users\anuraag.k\HCL\hclonetest\workspace_pt
            project: PT1
            suite: Test1
            imShared: 
            configFile: 
            duration:
            exportLog: 
            exportStatReportList: 
            exportStats: D:\reports\
            exportStatsFormat: 
            exportStatsHtml: 
            labels: l1
            overrideRmLabels:
            overwrite: 
            publish: https://master-hcl.tp-k8s.nonprod.hclpnp.com/#project.name=A_P2&teamspace.name=Initial%20Team%20Space
            publishFor: 
            publishReports: 
            rate:
            reportHistory:
            results: MyResult
            swapDatasets:
            userComments: 
            users:
            varFile:
            vmArgs:
