name: HCL OneTest Performance

on: workflow_dispatch

jobs:
    WebUI-Action:
        runs-on: self-hosted
        name: HCL OneTest Performance
        steps:
         - name: HCL OneTest Performance
           uses: anuraag-k/PerformanceTestAction@main
           with:
            workspace: C:\Users\anuraag.k\HCL\hclonetest\workspace
            project: PT1
            suite: Test1
